/********************************************************************
* ReconSelector_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ReconSelector_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableReconSelector_dict();
extern void G__cpp_setup_inheritanceReconSelector_dict();
extern void G__cpp_setup_typetableReconSelector_dict();
extern void G__cpp_setup_memvarReconSelector_dict();
extern void G__cpp_setup_globalReconSelector_dict();
extern void G__cpp_setup_memfuncReconSelector_dict();
extern void G__cpp_setup_funcReconSelector_dict();
extern void G__set_cpp_environmentReconSelector_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ReconSelector/ReconSelector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ReconSelector_dictLN_TClass;
extern G__linked_taginfo G__ReconSelector_dictLN_TBuffer;
extern G__linked_taginfo G__ReconSelector_dictLN_TMemberInspector;
extern G__linked_taginfo G__ReconSelector_dictLN_TObject;
extern G__linked_taginfo G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__ReconSelector_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ReconSelector_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ReconSelector_dictLN_TList;
extern G__linked_taginfo G__ReconSelector_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ReconSelector_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ReconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ReconSelector_dictLN_TTree;
extern G__linked_taginfo G__ReconSelector_dictLN_TBranch;
extern G__linked_taginfo G__ReconSelector_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__ReconSelector_dictLN_TSelector;
extern G__linked_taginfo G__ReconSelector_dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__ReconSelector_dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__ReconSelector_dictLN_TH1F;
extern G__linked_taginfo G__ReconSelector_dictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__ReconSelector_dictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__ReconSelector_dictLN_TH2F;
extern G__linked_taginfo G__ReconSelector_dictLN_ReconSelector;
extern G__linked_taginfo G__ReconSelector_dictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__ReconSelector_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ReconSelector_dictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__ReconSelector_dictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
