//
// File generated by /usr/local/root_v5.34.21/bin/rootcint at Mon Oct 13 12:14:11 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME ReconSelector_dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "ReconSelector_dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void ReconSelector_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_ReconSelector(void *p = 0);
   static void *newArray_ReconSelector(Long_t size, void *p);
   static void delete_ReconSelector(void *p);
   static void deleteArray_ReconSelector(void *p);
   static void destruct_ReconSelector(void *p);
   static void streamer_ReconSelector(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::ReconSelector*)
   {
      ::ReconSelector *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::ReconSelector >(0);
      static ::ROOT::TGenericClassInfo 
         instance("ReconSelector", ::ReconSelector::Class_Version(), "./ReconSelector/ReconSelector.h", 27,
                  typeid(::ReconSelector), DefineBehavior(ptr, ptr),
                  &::ReconSelector::Dictionary, isa_proxy, 0,
                  sizeof(::ReconSelector) );
      instance.SetNew(&new_ReconSelector);
      instance.SetNewArray(&newArray_ReconSelector);
      instance.SetDelete(&delete_ReconSelector);
      instance.SetDeleteArray(&deleteArray_ReconSelector);
      instance.SetDestructor(&destruct_ReconSelector);
      instance.SetStreamerFunc(&streamer_ReconSelector);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::ReconSelector*)
   {
      return GenerateInitInstanceLocal((::ReconSelector*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::ReconSelector*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
atomic_TClass_ptr ReconSelector::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *ReconSelector::Class_Name()
{
   return "ReconSelector";
}

//______________________________________________________________________________
const char *ReconSelector::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ReconSelector*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int ReconSelector::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ReconSelector*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void ReconSelector::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ReconSelector*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *ReconSelector::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ReconSelector*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void ReconSelector::Streamer(TBuffer &R__b)
{
   // Stream an object of class ReconSelector.

   TSelector::Streamer(R__b);
}

//______________________________________________________________________________
void ReconSelector::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class ReconSelector.
      TClass *R__cl = ::ReconSelector::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fChain", &fChain);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fNumberOfEvents", &fNumberOfEvents);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*parent_energy", &parent_energy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*parent_pdg", &parent_pdg);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "event_id", &event_id);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*volume", &volume);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*particle", &particle);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "n_active", &n_active);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*et", &et);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*ex", &ex);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*ey", &ey);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*ez", &ez);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*dt", &dt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*dz", &dz);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*dr", &dr);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*edep", &edep);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*edep_nuclear", &edep_nuclear);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*edep_electron", &edep_electron);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*eqch", &eqch);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*quenchingfactor", &quenchingfactor);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_parent_energy", &b_parent_energy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_parent_pdg", &b_parent_pdg);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_event_id", &b_event_id);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_volume", &b_volume);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_particle", &b_particle);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_n_active", &b_n_active);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_et", &b_et);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ex", &b_ex);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ey", &b_ey);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ez", &b_ez);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dt", &b_dt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dz", &b_dz);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dr", &b_dr);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_edep", &b_edep);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_edep_nuclear", &b_edep_nuclear);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_edep_electron", &b_edep_electron);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_eqch", &b_eqch);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_quenchingfactor", &b_quenchingfactor);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist2DGap", &Hist2DGap);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*QuenchingFactor", &QuenchingFactor);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist2D", &Hist2D);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist2DXYslice1", &Hist2DXYslice1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist2DXYslice2", &Hist2DXYslice2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist2DXYslice3", &Hist2DXYslice3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist2Dnuclear", &Hist2Dnuclear);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist2DXYnuclearslice1", &Hist2DXYnuclearslice1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist2DXYnuclearslice2", &Hist2DXYnuclearslice2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist2DXYnuclearslice3", &Hist2DXYnuclearslice3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist2Dsingle", &Hist2Dsingle);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist2DXYsingleslice1", &Hist2DXYsingleslice1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist2DXYsingleslice2", &Hist2DXYsingleslice2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist2DXYsingleslice3", &Hist2DXYsingleslice3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist2Dsinglenuclear", &Hist2Dsinglenuclear);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist2DXYsinglenuclearslice1", &Hist2DXYsinglenuclearslice1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist2DXYsinglenuclearslice2", &Hist2DXYsinglenuclearslice2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist2DXYsinglenuclearslice3", &Hist2DXYsinglenuclearslice3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist2DYZsingle", &Hist2DYZsingle);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist2DYZsinglenuclear", &Hist2DYZsinglenuclear);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist2DYZ", &Hist2DYZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist2DYZnuclear", &Hist2DYZnuclear);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist2DXZ", &Hist2DXZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist2DXZnuclear", &Hist2DXZnuclear);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist1DNRcountsslice1", &Hist1DNRcountsslice1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist1DNRcountsslice2", &Hist1DNRcountsslice2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist1DNRcountsslice3", &Hist1DNRcountsslice3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist1DNRcountsslice4", &Hist1DNRcountsslice4);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist1DTPCedep", &Hist1DTPCedep);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist1DTPCedep_nuclear", &Hist1DTPCedep_nuclear);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist1DTPCedep_electron", &Hist1DTPCedep_electron);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist1DNVedep", &Hist1DNVedep);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist1DNVedep_nuclear", &Hist1DNVedep_nuclear);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*Hist1DNVedep_electron", &Hist1DNVedep_electron);
      TSelector::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_ReconSelector(void *p) {
      return  p ? new(p) ::ReconSelector : new ::ReconSelector;
   }
   static void *newArray_ReconSelector(Long_t nElements, void *p) {
      return p ? new(p) ::ReconSelector[nElements] : new ::ReconSelector[nElements];
   }
   // Wrapper around operator delete
   static void delete_ReconSelector(void *p) {
      delete ((::ReconSelector*)p);
   }
   static void deleteArray_ReconSelector(void *p) {
      delete [] ((::ReconSelector*)p);
   }
   static void destruct_ReconSelector(void *p) {
      typedef ::ReconSelector current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_ReconSelector(TBuffer &buf, void *obj) {
      ((::ReconSelector*)obj)->::ReconSelector::Streamer(buf);
   }
} // end of namespace ROOT for class ::ReconSelector

/********************************************************
* ReconSelector_dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableReconSelector_dict();

extern "C" void G__set_cpp_environmentReconSelector_dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("ReconSelector/ReconSelector.h");
  G__cpp_reset_tagtableReconSelector_dict();
}
#include <new>
extern "C" int G__cpp_dllrevReconSelector_dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* ReconSelector */
static int G__ReconSelector_dict_578_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ReconSelector* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ReconSelector((TTree*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) ReconSelector((TTree*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new ReconSelector[n];
       } else {
         p = new((void*) gvp) ReconSelector[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new ReconSelector;
       } else {
         p = new((void*) gvp) ReconSelector;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ReconSelector_dictLN_ReconSelector));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ReconSelector_dict_578_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ReconSelector::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ReconSelector_dict_578_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ReconSelector::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ReconSelector_dict_578_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ReconSelector::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ReconSelector_dict_578_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ReconSelector::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ReconSelector_dict_578_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ReconSelector*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ReconSelector_dict_578_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ReconSelector::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ReconSelector_dict_578_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ReconSelector::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ReconSelector_dict_578_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ReconSelector::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ReconSelector_dict_578_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ReconSelector::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef ReconSelector G__TReconSelector;
static int G__ReconSelector_dict_578_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (ReconSelector*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((ReconSelector*) (soff+(sizeof(ReconSelector)*i)))->~G__TReconSelector();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (ReconSelector*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((ReconSelector*) (soff))->~G__TReconSelector();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* ReconSelector */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncReconSelector_dict {
 public:
  G__Sizep2memfuncReconSelector_dict(): p(&G__Sizep2memfuncReconSelector_dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncReconSelector_dict::*p)();
};

size_t G__get_sizep2memfuncReconSelector_dict()
{
  G__Sizep2memfuncReconSelector_dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceReconSelector_dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__ReconSelector_dictLN_ReconSelector))) {
     ReconSelector *G__Lderived;
     G__Lderived=(ReconSelector*)0x1000;
     {
       TSelector *G__Lpbase=(TSelector*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ReconSelector_dictLN_ReconSelector),G__get_linked_tagnum(&G__ReconSelector_dictLN_TSelector),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ReconSelector_dictLN_ReconSelector),G__get_linked_tagnum(&G__ReconSelector_dictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableReconSelector_dict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* ReconSelector */
static void G__setup_memvarReconSelector(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__ReconSelector_dictLN_ReconSelector));
   { ReconSelector *p; p=(ReconSelector*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fChain)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TTree),-1,-1,1,"fChain=",0,"!pointer to the analyzed TTree or TChain");
   G__memvar_setup((void*)((long)(&p->fNumberOfEvents)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fNumberOfEvents=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->parent_energy)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"parent_energy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->parent_pdg)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,1,"parent_pdg=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->event_id)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"event_id=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->volume)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlETStringcOallocatorlETStringgRsPgR),G__defined_typename("vector<TString>"),-1,1,"volume=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->particle)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlETStringcOallocatorlETStringgRsPgR),G__defined_typename("vector<TString>"),-1,1,"particle=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->n_active)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"n_active=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->et)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"et=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ex)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"ex=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ey)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"ey=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ez)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"ez=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dt)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"dt=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dz)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"dz=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dr)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"dr=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->edep)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"edep=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->edep_nuclear)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"edep_nuclear=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->edep_electron)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"edep_electron=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->eqch)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"eqch=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->quenchingfactor)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"quenchingfactor=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->b_parent_energy)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_parent_energy=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_parent_pdg)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_parent_pdg=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_event_id)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_event_id=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_volume)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_volume=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_particle)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_particle=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_n_active)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_n_active=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_et)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_et=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ex)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_ex=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ey)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_ey=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ez)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_ez=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dt)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_dt=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dz)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_dz=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dr)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_dr=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_edep)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_edep=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_edep_nuclear)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_edep_nuclear=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_edep_electron)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_edep_electron=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_eqch)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_eqch=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_quenchingfactor)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_quenchingfactor=",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"Hist2DGap=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"QuenchingFactor=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"Hist2D=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"Hist2DXYslice1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"Hist2DXYslice2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"Hist2DXYslice3=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"Hist2Dnuclear=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"Hist2DXYnuclearslice1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"Hist2DXYnuclearslice2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"Hist2DXYnuclearslice3=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"Hist2Dsingle=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"Hist2DXYsingleslice1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"Hist2DXYsingleslice2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"Hist2DXYsingleslice3=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"Hist2Dsinglenuclear=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"Hist2DXYsinglenuclearslice1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"Hist2DXYsinglenuclearslice2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"Hist2DXYsinglenuclearslice3=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"Hist2DYZsingle=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"Hist2DYZsinglenuclear=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"Hist2DYZ=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"Hist2DYZnuclear=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"Hist2DXZ=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"Hist2DXZnuclear=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"Hist1DNRcountsslice1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"Hist1DNRcountsslice2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"Hist1DNRcountsslice3=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"Hist1DNRcountsslice4=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"Hist1DTPCedep=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"Hist1DTPCedep_nuclear=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"Hist1DTPCedep_electron=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"Hist1DNVedep=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"Hist1DNVedep_nuclear=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"Hist1DNVedep_electron=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarReconSelector_dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncReconSelector(void) {
   /* ReconSelector */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__ReconSelector_dictLN_ReconSelector));
   G__memfunc_setup("ReconSelector",1336,G__ReconSelector_dict_578_0_1, 105, G__get_linked_tagnum(&G__ReconSelector_dictLN_ReconSelector), -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 '0' -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Version",742,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Begin",485,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SlaveBegin",992,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Notify",633,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Process",735,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetEntry",818,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 0, 
"n - 'Long64_t' 0 - entry i - 'Int_t' 0 '0' getall", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetOption",933,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetObject",899,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TObject' - 0 - obj", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetInputList",1240,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TList' - 0 - input", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetOutputList",1357,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__ReconSelector_dictLN_TList), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SlaveTerminate",1444,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Terminate",937,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("BookHistograms",1452,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FillHistograms",1448,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__ReconSelector_dict_578_0_17, 85, G__get_linked_tagnum(&G__ReconSelector_dictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&ReconSelector::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__ReconSelector_dict_578_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ReconSelector::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__ReconSelector_dict_578_0_19, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&ReconSelector::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__ReconSelector_dict_578_0_20, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&ReconSelector::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__ReconSelector_dictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__ReconSelector_dict_578_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__ReconSelector_dict_578_0_25, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ReconSelector::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__ReconSelector_dict_578_0_26, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ReconSelector::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__ReconSelector_dict_578_0_27, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ReconSelector::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__ReconSelector_dict_578_0_28, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ReconSelector::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~ReconSelector", 1462, G__ReconSelector_dict_578_0_29, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncReconSelector_dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalReconSelector_dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcReconSelector_dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__ReconSelector_dictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TBranch = { "TBranch" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TSelector = { "TSelector" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TH1F = { "TH1F" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TH2F = { "TH2F" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_ReconSelector = { "ReconSelector" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableReconSelector_dict() {
  G__ReconSelector_dictLN_TClass.tagnum = -1 ;
  G__ReconSelector_dictLN_TBuffer.tagnum = -1 ;
  G__ReconSelector_dictLN_TMemberInspector.tagnum = -1 ;
  G__ReconSelector_dictLN_TObject.tagnum = -1 ;
  G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__ReconSelector_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__ReconSelector_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ReconSelector_dictLN_TList.tagnum = -1 ;
  G__ReconSelector_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__ReconSelector_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ReconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__ReconSelector_dictLN_TTree.tagnum = -1 ;
  G__ReconSelector_dictLN_TBranch.tagnum = -1 ;
  G__ReconSelector_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__ReconSelector_dictLN_TSelector.tagnum = -1 ;
  G__ReconSelector_dictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__ReconSelector_dictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__ReconSelector_dictLN_TH1F.tagnum = -1 ;
  G__ReconSelector_dictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__ReconSelector_dictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__ReconSelector_dictLN_TH2F.tagnum = -1 ;
  G__ReconSelector_dictLN_ReconSelector.tagnum = -1 ;
  G__ReconSelector_dictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__ReconSelector_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ReconSelector_dictLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__ReconSelector_dictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableReconSelector_dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TClass);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TObject);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TList);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TTree);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TBranch);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TSelector);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TH1F);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TH2F);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_ReconSelector),sizeof(ReconSelector),-1,29952,(char*)NULL,G__setup_memvarReconSelector,G__setup_memfuncReconSelector);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupReconSelector_dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupReconSelector_dict()");
  G__set_cpp_environmentReconSelector_dict();
  G__cpp_setup_tagtableReconSelector_dict();

  G__cpp_setup_inheritanceReconSelector_dict();

  G__cpp_setup_typetableReconSelector_dict();

  G__cpp_setup_memvarReconSelector_dict();

  G__cpp_setup_memfuncReconSelector_dict();
  G__cpp_setup_globalReconSelector_dict();
  G__cpp_setup_funcReconSelector_dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncReconSelector_dict();
  return;
}
class G__cpp_setup_initReconSelector_dict {
  public:
    G__cpp_setup_initReconSelector_dict() { G__add_setup_func("ReconSelector_dict",(G__incsetup)(&G__cpp_setupReconSelector_dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initReconSelector_dict() { G__remove_setup_func("ReconSelector_dict"); }
};
G__cpp_setup_initReconSelector_dict G__cpp_setup_initializerReconSelector_dict;

