/********************************************************************
* mcneutronMain_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error mcneutronMain_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablemcneutronMain_dict();
extern void G__cpp_setup_inheritancemcneutronMain_dict();
extern void G__cpp_setup_typetablemcneutronMain_dict();
extern void G__cpp_setup_memvarmcneutronMain_dict();
extern void G__cpp_setup_globalmcneutronMain_dict();
extern void G__cpp_setup_memfuncmcneutronMain_dict();
extern void G__cpp_setup_funcmcneutronMain_dict();
extern void G__set_cpp_environmentmcneutronMain_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "dstreeneutronSelector/dstreeneutronSelector.h"
#include "reconneutronSelector/reconneutronSelector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__mcneutronMain_dictLN_TClass;
extern G__linked_taginfo G__mcneutronMain_dictLN_TBuffer;
extern G__linked_taginfo G__mcneutronMain_dictLN_TMemberInspector;
extern G__linked_taginfo G__mcneutronMain_dictLN_TObject;
extern G__linked_taginfo G__mcneutronMain_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__mcneutronMain_dictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__mcneutronMain_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__mcneutronMain_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mcneutronMain_dictLN_TList;
extern G__linked_taginfo G__mcneutronMain_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__mcneutronMain_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mcneutronMain_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__mcneutronMain_dictLN_TTree;
extern G__linked_taginfo G__mcneutronMain_dictLN_TBranch;
extern G__linked_taginfo G__mcneutronMain_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__mcneutronMain_dictLN_TSelector;
extern G__linked_taginfo G__mcneutronMain_dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__mcneutronMain_dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__mcneutronMain_dictLN_TH1F;
extern G__linked_taginfo G__mcneutronMain_dictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__mcneutronMain_dictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__mcneutronMain_dictLN_TH2F;
extern G__linked_taginfo G__mcneutronMain_dictLN_TNtuple;
extern G__linked_taginfo G__mcneutronMain_dictLN_dstreeneutronSelector;
extern G__linked_taginfo G__mcneutronMain_dictLN_TRint;
extern G__linked_taginfo G__mcneutronMain_dictLN_reconneutronSelector;
extern G__linked_taginfo G__mcneutronMain_dictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__mcneutronMain_dictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mcneutronMain_dictLN_vectorlETNtuplemUcOallocatorlETNtuplemUgRsPgR;
extern G__linked_taginfo G__mcneutronMain_dictLN_reverse_iteratorlEvectorlETNtuplemUcOallocatorlETNtuplemUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mcneutronMain_dictLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR;
extern G__linked_taginfo G__mcneutronMain_dictLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mcneutronMain_dictLN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR;
extern G__linked_taginfo G__mcneutronMain_dictLN_reverse_iteratorlEvectorlETH2FmUcOallocatorlETH2FmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mcneutronMain_dictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__mcneutronMain_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mcneutronMain_dictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__mcneutronMain_dictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
