/********************************************************************
* reconneutronMain_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error reconneutronMain_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablereconneutronMain_dict();
extern void G__cpp_setup_inheritancereconneutronMain_dict();
extern void G__cpp_setup_typetablereconneutronMain_dict();
extern void G__cpp_setup_memvarreconneutronMain_dict();
extern void G__cpp_setup_globalreconneutronMain_dict();
extern void G__cpp_setup_memfuncreconneutronMain_dict();
extern void G__cpp_setup_funcreconneutronMain_dict();
extern void G__set_cpp_environmentreconneutronMain_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "reconneutronClass.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__reconneutronMain_dictLN_TClass;
extern G__linked_taginfo G__reconneutronMain_dictLN_TBuffer;
extern G__linked_taginfo G__reconneutronMain_dictLN_TMemberInspector;
extern G__linked_taginfo G__reconneutronMain_dictLN_TObject;
extern G__linked_taginfo G__reconneutronMain_dictLN_TString;
extern G__linked_taginfo G__reconneutronMain_dictLN_string;
extern G__linked_taginfo G__reconneutronMain_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__reconneutronMain_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__reconneutronMain_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__reconneutronMain_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__reconneutronMain_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__reconneutronMain_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__reconneutronMain_dictLN_TChain;
extern G__linked_taginfo G__reconneutronMain_dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__reconneutronMain_dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__reconneutronMain_dictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__reconneutronMain_dictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__reconneutronMain_dictLN_TNtuple;
extern G__linked_taginfo G__reconneutronMain_dictLN_TRint;
extern G__linked_taginfo G__reconneutronMain_dictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__reconneutronMain_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__reconneutronMain_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__reconneutronMain_dictLN_Event;
extern G__linked_taginfo G__reconneutronMain_dictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__reconneutronMain_dictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__reconneutronMain_dictLN_reconneutronClass;
extern G__linked_taginfo G__reconneutronMain_dictLN_vectorlEPlotscOallocatorlEPlotsgRsPgR;
extern G__linked_taginfo G__reconneutronMain_dictLN_reverse_iteratorlEvectorlEPlotscOallocatorlEPlotsgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__reconneutronMain_dictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__reconneutronMain_dictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__reconneutronMain_dictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__reconneutronMain_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
